# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1exNtugRAUeuRo0XVT1wFDXYeIZuemFiM
"""

# ステップ１　インポート
import numpy as np
import matplotlib.pyplot as plt

# ステップ２　グラフの領域作成
fig, axes = plt.subplots(2, 3, tight_layout=True, facecolor="white")

# 折れ線グラフ
y0 = [1, 2, -5, 2]
axes[0, 0].plot(y0)

# sin関数
x01 = np.linspace(0, 10, 100)
y01 = 2 + 2 * np.sin(2 * x)
axes[0, 1].plot(x01, y01)

# ヒストグラム
x02 = np.random. normal(15, 5, 1000)
axes[0, 2].hist(x02)

# 散布図
np.random.seed(3)
x10 = 4 + np.random.normal(0, 2, 60)
y10 = 4 + np.random.normal(0, 2, len(x10))
axes[1, 0].scatter(x10, y10)